import type { 
  AthleteProfile, 
  Workout, 
  AssignedWorkout, 
  PersonalRecord, 
  TrainingPace, 
  Goal,
  WeeklyStats,
  MonthlyStats
} from '@/lib/types'

// Mock athlete profile
export const mockAthleteProfile: AthleteProfile = {
  id: 'athlete-1',
  userId: 'user-1',
  name: 'Sarah Johnson',
  email: 'sarah.johnson@email.com',
  photoURL: undefined,
  dateOfBirth: '1998-05-15',
  gender: 'female',
  height: 168,
  weight: 54,
  events: ['800m', '1500m', '3000m'],
  personalRecords: [
    { id: 'pr-1', event: '800m', time: '2:05.34', date: '2024-06-15', location: 'Eugene, OR', competition: 'Olympic Trials' },
    { id: 'pr-2', event: '1500m', time: '4:12.87', date: '2024-05-20', location: 'Los Angeles, CA', competition: 'USATF Championships' },
    { id: 'pr-3', event: '3000m', time: '8:58.12', date: '2024-04-10', location: 'Stanford, CA', competition: 'Stanford Invitational' },
    { id: 'pr-4', event: 'Mile', time: '4:32.45', date: '2024-02-18', location: 'Boston, MA', competition: 'New Balance Indoor GP' },
  ],
  seasonBests: [
    { id: 'sb-1', event: '800m', time: '2:06.12', date: '2024-07-01', location: 'Paris, FR' },
    { id: 'sb-2', event: '1500m', time: '4:14.33', date: '2024-06-28', location: 'Monaco' },
  ],
  trainingPaces: [
    { id: 'pace-1', type: 'easy', pace: '7:30-8:00/mi', description: 'Recovery and easy days' },
    { id: 'pace-2', type: 'tempo', pace: '5:45-6:00/mi', description: 'Sustained effort runs' },
    { id: 'pace-3', type: 'threshold', pace: '5:20-5:35/mi', description: 'Lactate threshold work' },
    { id: 'pace-4', type: 'interval', pace: '4:45-5:00/mi', description: '1000m-1600m intervals' },
    { id: 'pace-5', type: 'repetition', pace: '67-70s/400m', description: 'Fast reps and speed work' },
    { id: 'pace-6', type: 'race', pace: '65s/400m (800m)', description: 'Race pace for 800m' },
  ],
  goals: [
    { id: 'goal-1', title: 'Sub-2:05 800m', targetTime: '2:04.99', targetEvent: '800m', targetDate: '2025-06-01', status: 'active', createdAt: new Date() },
    { id: 'goal-2', title: 'Make World Championships Team', targetEvent: '1500m', targetDate: '2025-07-15', status: 'active', createdAt: new Date() },
    { id: 'goal-3', title: 'Break 4:30 Mile', targetTime: '4:29.99', targetEvent: 'Mile', targetDate: '2025-02-01', status: 'active', createdAt: new Date() },
  ],
  coachId: 'coach-1',
  createdAt: new Date(),
  updatedAt: new Date(),
}

// Mock workouts library
export const mockWorkouts: Workout[] = [
  {
    id: 'workout-1',
    title: 'Easy Recovery Run',
    type: 'easy',
    description: 'Easy aerobic run at conversational pace. Focus on relaxation and recovery.',
    duration: 45,
    distance: 8,
    warmup: '10 min walk/jog',
    cooldown: '5 min walk, stretching',
    notes: 'Keep heart rate under 140 BPM',
    createdBy: 'coach-1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'workout-2',
    title: '800m Intervals',
    type: 'intervals',
    description: 'Speed work focusing on 800m race pace and lactate tolerance.',
    duration: 60,
    sets: [
      { id: 'set-1', reps: 6, distance: '800m', pace: '2:32-2:36', rest: '3:00 jog recovery' },
    ],
    warmup: '2 mile easy jog, dynamic stretching, 4x100m strides',
    cooldown: '1.5 mile easy jog, stretching',
    notes: 'Focus on even splits. First rep should feel controlled.',
    createdBy: 'coach-1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'workout-3',
    title: 'Long Run',
    type: 'long_run',
    description: 'Aerobic base building. Progressive pace - start easy, finish moderate.',
    duration: 90,
    distance: 14,
    warmup: 'Start very easy for first mile',
    cooldown: 'Walk 5 min, foam roll',
    notes: 'Hydrate every 30 min. Take gels if needed.',
    createdBy: 'coach-1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'workout-4',
    title: 'Tempo Run',
    type: 'tempo',
    description: 'Sustained effort at lactate threshold pace.',
    duration: 55,
    distance: 10,
    sets: [
      { id: 'set-2', reps: 1, distance: '5 miles', pace: '5:45-5:50/mi', rest: 'N/A' },
    ],
    warmup: '2 mile easy, 4x100m strides',
    cooldown: '1.5 mile easy',
    notes: 'Should feel comfortably hard. Breathing should be controlled but noticeable.',
    createdBy: 'coach-1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'workout-5',
    title: 'Hill Repeats',
    type: 'hill_repeats',
    description: 'Power and strength development on moderate grade hill.',
    duration: 50,
    sets: [
      { id: 'set-3', reps: 8, duration: '90 seconds uphill', pace: 'Hard effort', rest: 'Jog down recovery' },
    ],
    warmup: '1.5 mile easy, dynamic drills',
    cooldown: '1 mile easy, stretching',
    notes: 'Focus on powerful arm drive and high knees.',
    createdBy: 'coach-1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'workout-6',
    title: 'Rest Day',
    type: 'rest',
    description: 'Complete rest. Light stretching or yoga optional.',
    duration: 0,
    notes: 'Focus on sleep, nutrition, and recovery. Foam rolling recommended.',
    createdBy: 'coach-1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'workout-7',
    title: 'Fartlek',
    type: 'fartlek',
    description: 'Unstructured speed play mixing fast and slow running.',
    duration: 50,
    distance: 8,
    notes: '6x (2 min hard, 2 min easy) within the run. Let feel dictate intensity.',
    warmup: '1 mile easy',
    cooldown: '1 mile easy',
    createdBy: 'coach-1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'workout-8',
    title: 'Track Workout - 400s',
    type: 'intervals',
    description: 'Speed development focusing on leg turnover.',
    duration: 55,
    sets: [
      { id: 'set-4', reps: 10, distance: '400m', pace: '68-70 seconds', rest: '90 sec standing' },
    ],
    warmup: '2 mile jog, drills, 4x100m strides',
    cooldown: '1.5 mile jog',
    notes: 'Maintain consistent splits. Last 2 should not be much faster than first 2.',
    createdBy: 'coach-1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Generate dates for the current week and upcoming weeks
function getDateString(daysFromToday: number): string {
  const date = new Date()
  date.setDate(date.getDate() + daysFromToday)
  return date.toISOString().split('T')[0]
}

// Mock assigned workouts for the athlete
export const mockAssignedWorkouts: AssignedWorkout[] = [
  {
    id: 'assigned-1',
    workoutId: 'workout-1',
    workout: mockWorkouts[0],
    athleteId: 'athlete-1',
    assignedBy: 'coach-1',
    scheduledDate: getDateString(-2),
    status: 'completed',
    completedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    actualDuration: 47,
    actualDistance: 8.2,
    perceivedEffort: 4,
    athleteNotes: 'Felt good, legs were fresh.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assigned-2',
    workoutId: 'workout-2',
    workout: mockWorkouts[1],
    athleteId: 'athlete-1',
    assignedBy: 'coach-1',
    scheduledDate: getDateString(-1),
    status: 'completed',
    completedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    actualDuration: 58,
    perceivedEffort: 8,
    athleteNotes: 'Hit all splits. Last two felt tough but controlled.',
    coachFeedback: 'Great work! Exactly what we wanted to see.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assigned-3',
    workoutId: 'workout-6',
    workout: mockWorkouts[5],
    athleteId: 'athlete-1',
    assignedBy: 'coach-1',
    scheduledDate: getDateString(0),
    status: 'scheduled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assigned-4',
    workoutId: 'workout-4',
    workout: mockWorkouts[3],
    athleteId: 'athlete-1',
    assignedBy: 'coach-1',
    scheduledDate: getDateString(1),
    status: 'scheduled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assigned-5',
    workoutId: 'workout-1',
    workout: mockWorkouts[0],
    athleteId: 'athlete-1',
    assignedBy: 'coach-1',
    scheduledDate: getDateString(2),
    status: 'scheduled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assigned-6',
    workoutId: 'workout-5',
    workout: mockWorkouts[4],
    athleteId: 'athlete-1',
    assignedBy: 'coach-1',
    scheduledDate: getDateString(3),
    status: 'scheduled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assigned-7',
    workoutId: 'workout-1',
    workout: mockWorkouts[0],
    athleteId: 'athlete-1',
    assignedBy: 'coach-1',
    scheduledDate: getDateString(4),
    status: 'scheduled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assigned-8',
    workoutId: 'workout-3',
    workout: mockWorkouts[2],
    athleteId: 'athlete-1',
    assignedBy: 'coach-1',
    scheduledDate: getDateString(5),
    status: 'scheduled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assigned-9',
    workoutId: 'workout-6',
    workout: mockWorkouts[5],
    athleteId: 'athlete-1',
    assignedBy: 'coach-1',
    scheduledDate: getDateString(6),
    status: 'scheduled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Mock weekly stats
export const mockWeeklyStats: WeeklyStats[] = [
  { week: 'Week 1', totalDistance: 45, totalDuration: 320, workoutsCompleted: 6, averageEffort: 5.5 },
  { week: 'Week 2', totalDistance: 52, totalDuration: 380, workoutsCompleted: 6, averageEffort: 6.2 },
  { week: 'Week 3', totalDistance: 48, totalDuration: 350, workoutsCompleted: 5, averageEffort: 6.8 },
  { week: 'Week 4', totalDistance: 38, totalDuration: 280, workoutsCompleted: 5, averageEffort: 4.5 },
  { week: 'Week 5', totalDistance: 55, totalDuration: 400, workoutsCompleted: 6, averageEffort: 6.5 },
  { week: 'Week 6', totalDistance: 58, totalDuration: 420, workoutsCompleted: 7, averageEffort: 6.8 },
  { week: 'Week 7', totalDistance: 50, totalDuration: 365, workoutsCompleted: 6, averageEffort: 7.0 },
  { week: 'Week 8', totalDistance: 42, totalDuration: 310, workoutsCompleted: 5, averageEffort: 5.0 },
]

// Mock monthly stats
export const mockMonthlyStats: MonthlyStats[] = [
  { month: 'Jan', totalDistance: 180, totalDuration: 1320, workoutsCompleted: 24, prsAchieved: 0 },
  { month: 'Feb', totalDistance: 195, totalDuration: 1420, workoutsCompleted: 25, prsAchieved: 1 },
  { month: 'Mar', totalDistance: 210, totalDuration: 1540, workoutsCompleted: 26, prsAchieved: 0 },
  { month: 'Apr', totalDistance: 205, totalDuration: 1500, workoutsCompleted: 25, prsAchieved: 1 },
  { month: 'May', totalDistance: 220, totalDuration: 1600, workoutsCompleted: 27, prsAchieved: 1 },
  { month: 'Jun', totalDistance: 200, totalDuration: 1460, workoutsCompleted: 24, prsAchieved: 2 },
]

// Mock athletes for coach view
export const mockAthletes: AthleteProfile[] = [
  mockAthleteProfile,
  {
    ...mockAthleteProfile,
    id: 'athlete-2',
    userId: 'user-2',
    name: 'Michael Chen',
    email: 'michael.chen@email.com',
    gender: 'male',
    height: 180,
    weight: 70,
    events: ['400m', '800m'],
    personalRecords: [
      { id: 'pr-5', event: '400m', time: '46.82', date: '2024-06-15', location: 'Eugene, OR' },
      { id: 'pr-6', event: '800m', time: '1:48.23', date: '2024-05-20', location: 'Los Angeles, CA' },
    ],
  },
  {
    ...mockAthleteProfile,
    id: 'athlete-3',
    userId: 'user-3',
    name: 'Emma Williams',
    email: 'emma.williams@email.com',
    gender: 'female',
    height: 165,
    weight: 52,
    events: ['5000m', '10000m'],
    personalRecords: [
      { id: 'pr-7', event: '5000m', time: '15:28.45', date: '2024-05-10', location: 'Palo Alto, CA' },
      { id: 'pr-8', event: '10000m', time: '32:15.88', date: '2024-04-05', location: 'Stanford, CA' },
    ],
  },
  {
    ...mockAthleteProfile,
    id: 'athlete-4',
    userId: 'user-4',
    name: 'James Rodriguez',
    email: 'james.rodriguez@email.com',
    gender: 'male',
    height: 175,
    weight: 65,
    events: ['1500m', '3000m SC'],
    personalRecords: [
      { id: 'pr-9', event: '1500m', time: '3:38.12', date: '2024-06-20', location: 'Monaco' },
      { id: 'pr-10', event: '3000m SC', time: '8:22.45', date: '2024-05-15', location: 'Eugene, OR' },
    ],
  },
]
