import { clsx, type ClassValue } from 'clsx'
import { twMerge } from 'tailwind-merge'
import type { ExerciseLibraryItem, StrengthBlockExercise } from '@/lib/types'

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

/** Merges a workout's stored StrengthBlockExercise with the CURRENT
 *  Exercise Library entry it points at (if it still exists), so an edited
 *  video/instructions/name/category shows up everywhere immediately —
 *  "it's the same exercise" — instead of every workout being frozen with
 *  whatever the library looked like when it was added. Only targetSets/
 *  targetReps/targetDurationSec/notes stay as stored, since those really
 *  are workout-specific (how many sets THIS workout wants). Falls back to
 *  the stored snapshot fields if the library entry was since deleted, so a
 *  removed exercise doesn't go blank in workouts already built with it. */
export function resolveExerciseDisplay(
  ex: StrengthBlockExercise,
  libraryById: Map<string, ExerciseLibraryItem>,
  language: 'he' | 'en' = 'he',
): StrengthBlockExercise {
  const live = libraryById.get(ex.exerciseId)
  const merged: StrengthBlockExercise = live
    ? {
        ...ex,
        name: live.name,
        videoUrl: live.videoUrl,
        videoMuted: live.videoMuted,
        instructions: live.instructions,
        category: live.category ?? ex.category,
      }
    : ex
  if (language !== 'en') return merged
  // English athletes: prefer the AI-translated cache, falling back to
  // Hebrew if a translation hasn't landed yet (see lib/translate.ts) —
  // never show a blank field over showing Hebrew.
  return {
    ...merged,
    name: live?.nameEn || merged.name,
    instructions: live?.instructionsEn || merged.instructions,
    notes: ex.notesEn || merged.notes,
  }
}

/** Picks the language-appropriate copy of a coach-authored text field,
 *  falling back to Hebrew when no English translation is cached yet
 *  (new content, or a translation call that hasn't landed/failed) — an
 *  English athlete should never see a blank field. */
export function resolveText(
  language: 'he' | 'en',
  he: string | undefined | null,
  en: string | undefined | null,
): string {
  if (language === 'en' && en?.trim()) return en
  return he || ''
}

/** Translates a StrengthBlock's coach-editable label ("סט 1", "סופרסט 2",
 *  "מתיחה 1") for English athletes. These are a small closed set of
 *  patterns generated by the block builder (see strength-block-builder.tsx),
 *  so a plain word-swap covers them without needing an AI call/cache — any
 *  label that doesn't match one of these prefixes is left as-is. */
export function translateBlockLabel(label: string, language: 'he' | 'en'): string {
  if (language !== 'en' || !label) return label
  return label
    .replace(/^סופרסט/, 'Superset')
    .replace(/^מתיחה/, 'Stretch')
    .replace(/^חימום/, 'Warm-up')
    .replace(/^סבב/, 'Round')
    .replace(/^סט/, 'Set')
}

/** Formats a set's target (sets × reps, or sets × duration) with
 *  language-appropriate unit words — "3 sets × 10 reps" in English,
 *  "3 סטים × 10 חזרות" in Hebrew — instead of literally translating the
 *  Hebrew unit text. Pass `sets` as undefined when it's shown separately
 *  (e.g. one round of a superset, where the round number is its own
 *  label already). The reps value itself (free text, e.g. "8-12") is
 *  left as entered — it's almost always just digits/ranges. */
export function formatSetTarget(
  language: 'he' | 'en',
  reps: string,
  durationSec?: number | null,
  sets?: number,
): string {
  if (language === 'en') {
    const setsLabel = sets != null ? `${sets} sets × ` : ''
    return durationSec != null ? `Target: ${setsLabel}${durationSec} sec` : `Target: ${setsLabel}${reps} reps`
  }
  const setsLabel = sets != null ? `${sets} סטים × ` : ''
  return durationSec != null ? `יעד: ${setsLabel}${durationSec} שניות` : `יעד: ${setsLabel}${reps} חזרות`
}

/** Splits an exercise's free-text instructions into separate cue lines for
 *  bulleted display, instead of one dense paragraph. Prefers real newlines
 *  (coach entered one cue per line); falls back to splitting on Hebrew/
 *  English sentence-ending periods for older text saved as one paragraph
 *  (e.g. imported cues like "גב ישר. ברך לא נעולה."). */
export function instructionLines(text?: string | null): string[] {
  if (!text) return []
  const byNewline = text.split('\n').map((l) => l.trim()).filter(Boolean)
  if (byNewline.length > 1) return byNewline
  return text
    .split(/(?<=[.!?])\s+/)
    .map((l) => l.trim())
    .filter(Boolean)
}
